POST http://localhost:3001/api/questions  
Content-Type: application/json

{
    "prompt": "Los de cedula 13 son de la provincia de",
    "optionA": "Darien",
    "optionB": "Chorrera",
    "optionC": "Cocle",
    "optionD": "Panama Oeste",
    "asnwer": "optionD"
}
